### PR TITLE
Fix cone size for Muon Iso Run II

### PR DESCRIPTION
**Pull request by mschnepf**
Add function and variables for R=0.4 cone size for Muon Isolation

### CODE REVIEW

**Comment by HerrHorizontal** [comment]
Did you test, if it works?

**Comment by mschnepf** [comment]
Yes, it works. Excalibur with a fixed Arthus produce a bit different output than before the fix.

**Comment by HerrHorizontal** [comment]
Can you link the corresponding Artus changes?

**Comment by mschnepf** [comment]
Sure
https://github.com/mschnepf/Artus/commit/d2502c7cd950227bf8d3b88ba3bbb12f54d1c0f3

**Comment by HerrHorizontal** [comment]
Seems good to me. As far as @cheidecker has no concerns, we can merge.

**Pull request merged**
