### PR TITLE
Reduced trigger objects

### PR DESCRIPTION
**Pull request by ArturAkh**
Dear all,

I want to draw your attention to the re-implementation of the trigger-objects, aiming for a simpler approach more consistent with the procedures used by Trigger POGs. I oriented myself e.g. on:

https://github.com/Sam-Harper/usercode/blob/100XNtup/TrigTools/plugins/Ele32DoubleL1ToSingleL1Example.cc

With the new approach it would be now possible to move all knowledge needed to match trigger objects to HLT paths to the analysis level, since there, it is needed anyway (see our configurations). For the time-being I've implemented it as a separate class, but replace in the end the obsolete producers, if everyone agrees.

For now, there are no optimizations concerning runtime & space used. Since I use std::vectors of strings (I know, that's nasty), you would expect a strong performance loss. By now, it is mitigated by writing out only interesting trigger objects, which have at least one filter of interest. See here:

https://github.com/KIT-CMS/Kappa/blob/reduced_trigger_objects/Producers/python/KTuple_cff.py#L119

The runtime is in that way smaller, but about 5% more space is needed. Currently, I'm running a full 2017 skim with it, I'll see whether it is much bigger or not.

I'm open for suggestions, how to increase the efficiency. Some points I already now have in mind are the following:

1.  Use bits: I don't now, where the filter-names information is stored, `unpackFilterLabels()` function produces a std::vector of strings only for filters which are **passed** by the trigger object, so for each event different filters could be passed. So we need to access somehow the metadata of these filters to able to do the name <---> bit relation.

2. Search complexity of O(n):  for the std::vector of strings, the find function has a O(n) complexity. For an std::unordered_set, which uses hashes (but needs more space), the worst complexity is also O(n), but on average, you could achieve O(1), depending strongly on the hash function. Here, I'm also not that familiar, what could be the best hash function for strings. I've checked also the baskets used for  default hashing, and for some trigger objects with about 100 filters, there were already some baskets  with 10 filter names. But should still be better on average though, than the worst case.

Cheers,

Artur

### CODE REVIEW

**Comment by dsavoiu** [comment]
Hi Artur,

Thanks for taking the time to look into our trigger object situation in Kappa (I guess there's a lot that can still be improved here). Since I am also coincidentally working on understanding how triggers and trigger objects "work" in CMSSW, I thought I'd provide some feedback :)

However: I'm a bit confused as to the advantage of writing out the trigger filters as a `std::vector<std::string>` for every trigger object, as compared to the previous approach.
My main concern is that this will indeed increase the output size and result in a performance hit
when processing the trigger objects on analysis-level...

In the current approach (as I understand it), we write out _all_ the trigger filter names defined in a particular HLT menu, but only once per lumi-section (in the `Lumis`-Tree of our Kappa tuples). Then, for each trigger object in an event, we only write out a `std::vector<int>`, giving only the indices of the filters which it passed, so effectively the same information is written out in your version, but the filter strings
would then be stored for every event (and trigger object) instead of just once per lumisection.

In fact, this would probably be a good opportunity to optimize the storage even further, and store the
filter list (or a "regex-reduced" filter list) in the new `Runs` tree instead of the `Lumis` tree. The rationale
being that the trigger menu doesn't change during a run (and so the filter names and indices remain the same).

Could you please explain a little why this change is needed? You mentioned that it is to facilitate the matching of trigger objects to HLT paths to the analysis level, but shouldn't this already possible with the current structure? Could you maybe point to a use-case in your Artus analysis?

In any case, I'm curious to see how this change impacts the full 2017 skims you are currently doing. An increase of 5% would not be that large, but there might also the implications on both the Kappa skimming and the Artus analysis runtimes if we switch to vectors of `std::string`, so that might also be a thing to look into.

P.S. I'm not sure I fully understand what you mean by accessing the filter metadata. If you call `TriggerObjectStandAlone::filterNames()` you only get the names of the filters that the object passed, but if you want all the filter names for a trigger path, you can use the
`HLTConfigProvider::saveTageModules(const std::string& triggerPathName)` method (see [here](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/HLTrigger/HLTcore/interface/HLTConfigProvider.h#L110-L112))
It's also used in the `KTriggerObjectStandaloneProducer` ([here](https://github.com/KIT-CMS/Kappa/blob/master/Producers/interface/KTriggerObjectStandaloneProducer.h#L230)).

**Comment by ArturAkh** [comment]
Hi Daniel,

Thanks for your feedback!

The structure of the Trigger-Objects in Kappa is built up the following way:

HLTPath
----> filterSequences within HLTPath
        -----> triggerObject passing that filter sequence.

The main flaw of this structure is, that the relation triggerObject -----> (filter passed) is lost completely. The PatTriggerObject contains that relation. In turn, custom filter matches like in case of EGamma HLT recommendation are not possible (combine filterObject from **different** HLT paths to create a desired HLT from a looser one):
https://twiki.cern.ch/twiki/bin/viewauth/CMS/Egamma2017DataRecommendations#Single_Electron_Triggers

So you cannot access the trigger-object directly & you have to go through the full hierarchy, with the limitation to a certain HLT path. This hierarchy leads to a complicated structure in Artus for trigger object matching (nested for loops):

https://github.com/KIT-CMS/Artus/blob/master/KappaAnalysis/interface/Producers/TriggerMatchingProducers.h#L100-L174

The current reduction implemented:
https://github.com/KIT-CMS/Artus/blob/reduced_trigger_objects/KappaAnalysis/interface/Producers/TriggerMatchingProducers.h#L100-L156

And since you don't have to go down through the full hierarchy, you can reduce the amount of deltaR matched trigger-objects **directly** at the beginning:

https://github.com/KIT-CMS/Artus/blob/reduced_trigger_objects/KappaAnalysis/interface/Producers/TriggerMatchingProducers.h#L117-L123

This leads to a further runtime improvement of the analysis, which is not possible in the current hierarchy approach.

Furthermore, the hierarchy is not needed at KappaLevel, since you already have to induce it in your configuration (you still have to say, what to match), like here:

https://github.com/KIT-CMS/KITHiggsToTauTau/blob/master/python/data/ArtusConfigs/Run2MSSM2017/tt.py#L140-L147

These are the main reasons, why I'd propose to work on the new approach. But I agree with you, that using filter indices instead of strings would lead to a significant improvement. I'd like to access the metadata used by this function:

https://github.com/Sam-Harper/usercode/blob/100XNtup/TrigTools/plugins/Ele32DoubleL1ToSingleL1Example.cc#L101

One comment on it: it does **not** return all filter names available, but only the ones, which are passed by the trigger object.

I personally don't like the structure imposed by the HLTConfigProvider, at least as it is used in Kappa, since you are then restricted to a certain HLT path and the hierarchy. I'd like to have the available filter names directly.

And strictly speaking, we also do not take all filters possible but the ones used in the HLT paths. And the HLT paths used in Kappa are found by this pattern, as far as I understand:

https://github.com/KIT-CMS/Kappa/blob/master/Producers/python/KTuple_cff.py#L54-L64

So pretty equivalent to the filter regex pattern I've introduced, with the exception of jet triggers. The regex I use is adapted to H->tautau analysis, but it can be also changed/extended for other purposes.

**Comment by ArturAkh** [comment]
Some numbers  on synchronisation sample I skimmed twice for comparison:

Space consumption:

currently default approach:

```
du -hs --exclude=*.log /pnfs/desy.de/cms/tier2/store/user/aakhmets/higgs-kit/skimming/VBFM125_triggerobject_original_14-06-2018/
25G	/pnfs/desy.de/cms/tier2/store/user/aakhmets/higgs-kit/skimming/VBFM125_triggerobject_original_14-06-2018/
```

new approach:

```
du -hs --exclude=*.log /pnfs/desy.de/cms/tier2/store/user/aakhmets/higgs-kit/skimming/VBFM125_triggerobject_test_13-06-2018/
26G	/pnfs/desy.de/cms/tier2/store/user/aakhmets/higgs-kit/skimming/VBFM125_triggerobject_test_13-06-2018/
```

Runtime tested on kappa files from the same MINIAOD input file:

currently default approach:

```
Status: 93476/93476 - 00:00:00/00:02:07 - 735 / s - 100%    

real    2m15.752s
user    2m1.396s
sys     0m9.106s
```

new approach:

```
Status: 93476/93476 - 00:00:00/00:02:32 - 611 / s - 100%

real    2m42.109s
user    2m26.405s
sys     0m8.784s
```

Hm ok. So there is a loss of 20 % in runtime in analysis and 4 % more space is used. But better code readability and more flexible :) I think, with switching to an unordered set & or filter bits we could improve further.

What do you think? :)

**Comment by ArturAkh** [comment]
About walltimes in Kappa:
default approach: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Artur+Akhmetshin&refresh=60&table=Jobs&p=1&records=200&sorting%5B%5D=9&sorting%5B%5D=desc&activemenu=1&status=finished&site=&tid=180714_091040%3Aaakhmets_crab_VBFHToTauTauM125_RunIIFall17MiniAODv2_PU2017_13TeV_MINIAOD_powheg-pythia8_v1

new approach:
http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Artur+Akhmetshin&refresh=60&table=Jobs&p=1&records=200&sorting%5B%5D=9&sorting%5B%5D=desc&activemenu=2&status=finished&site=&tid=180713_160542%3Aaakhmets_crab_VBFHToTauTauM125_RunIIFall17MiniAODv2_PU2017_13TeV_MINIAOD_powheg-pythia8_v1

**Comment by ArturAkh** [comment]
Dear all,

Since this project is now a bit stale, since I don't find time to refine it to get the performance we had back, I'll merge this into dictchanges today evening, if you don't mind.

The performance loss in Artus/KITHiggs would be about 20% for 4 pipelines, but personally, I don't see much of it, if running on batch systems. Therefore, I'd also go for a merge of the pull request in the other repositories into dictchanges, if there are any objections and make an open issue instead of this.

For Kappa, this doesn't harm at all, since these developments were on a separate data format

**Pull request merged**
