### PR TITLE
Prefiring weight

### PR DESCRIPTION
**Pull request by greyxray**
this is the implementation of the recipe to add the prefiring weights per-event as described here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1ECALPrefiringWeightRecipe

### CODE REVIEW

**Review by ArturAkh — APPROVED** [review]
Changes so far fine with me, but I'm not an expert on these weight. I think Sebastian can comment more on this.

**Comment by greyxray** [comment]
an update from my side: the standard recipe that is provided by JETMET works actually only locally... this PR needs a dedicated update to include the map file Properly.

**Comment by greyxray** [comment]
@swozniewski are there any objections from you to merging this branch by chance? :)

**Review by swozniewski — APPROVED** [review]
thank you Olena! looks fine

**Pull request merged**
