### PR TITLE
[2017UL] Update to MiniAODv2.

### PR DESCRIPTION
**Pull request by RHofsaess**
Updated to MiniAODv2. 
Since Egamma scale and smearing is included, the egammaPostRecoSeq process was commented out in the kappaSkim_default_cfg.py.
The usage of MiniAODv2 has been validated. 
There is a small difference in the MET related quantities (O(1-10MeV)), but this is already observable in MiniAOD. 
(The reason is up to date unknown, but it is save to use as discussed in the CERN mattermost `MET Analyses` channel.)*

For the new amcatnlo MC in MiniAODv2, we had GC problems, since the PhedEx request do not work for those data set anymore.
Therefore, the file list has to be given explicitly (see the gc config for MC-MiniAODv2).
The list was created with:
https://github.com/KIT-CMS/gc_configs_for_embedding/blob/master/scripts/read_filelist_from_das.py

*Laurent Thomas: `It could indeed be a precision issue. I wouldn't worry so much if the effect is really below 10 MeV. We definitely saw differences of this size in NANOAOD when rerunning or not the MET tool. It might be a similar thing here.`

### CODE REVIEW

**Review by HerrHorizontal — APPROVED** [review]
Looks good. Many thanks :+1:

**Comment by HerrHorizontal** [comment]
Of course, it is quite ugly, that Grid-Control is not able anymore to figure the file list out by itself. This additional step in the workflow would be unnecessary if someone had maintained Grid-Control.

**Comment by HerrHorizontal** [comment]
Did you check, that after running with the new configuration for the ` BadPFMuonDzFilter` was added, it is indeed available in Excalibur?

**Comment by RHofsaess** [comment]
yes :+1:

**Pull request merged**
